valor1 = float(input("digite o primeiro numero: "))
valor2 = float(input("digite o segundo numero: "))
valor3 = float(input("digite o terceiro numero: "))
valor4 = float(input("digite o quarto numero: "))
valor5 = float(input("digite o quinto numero: "))
print ((valor1+valor2+valor3+valor4+valor5)/2)
